
apiVersion: v1
kind: Pod
metadata:
  name: my-cluster
spec:
  containers:
    - name: master
      image: my-master-image
      resources:
        requests:
          cpu: 0.5
          memory: 512Mi
        limits:
          cpu: 1
          memory: 1Gi
    - name: worker1
      image: my-worker-image
      resources:
        requests:
          cpu: 0.5
          memory: 512Mi
        limits:
          cpu: 1
          memory: 1Gi
    - name: worker2
      image: my-worker-image
      resources:
        requests:
          cpu: 0.5
          memory: 512Mi
        limits:
          cpu: 1
          memory: 1Gi
